// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOvboQf6RMpt3iaVjfweVmH26JuyQMlhA',
    appId: '1:740630534257:web:ff51a475a05642a1baa3d0',
    messagingSenderId: '740630534257',
    projectId: 'project-f3f7e',
    authDomain: 'project-f3f7e.firebaseapp.com',
    storageBucket: 'project-f3f7e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkPrNr0azI1Zy0an-AaMrRBWQCCOFM_U0',
    appId: '1:740630534257:android:0da2cd645ee6b4a1baa3d0',
    messagingSenderId: '740630534257',
    projectId: 'project-f3f7e',
    storageBucket: 'project-f3f7e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCED3WNLOQUffoavRIA0ofCuWJqhbAXWEw',
    appId: '1:740630534257:ios:89af14f31a33f9a1baa3d0',
    messagingSenderId: '740630534257',
    projectId: 'project-f3f7e',
    storageBucket: 'project-f3f7e.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCED3WNLOQUffoavRIA0ofCuWJqhbAXWEw',
    appId: '1:740630534257:ios:89af14f31a33f9a1baa3d0',
    messagingSenderId: '740630534257',
    projectId: 'project-f3f7e',
    storageBucket: 'project-f3f7e.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOvboQf6RMpt3iaVjfweVmH26JuyQMlhA',
    appId: '1:740630534257:web:81bded04791ca8c3baa3d0',
    messagingSenderId: '740630534257',
    projectId: 'project-f3f7e',
    authDomain: 'project-f3f7e.firebaseapp.com',
    storageBucket: 'project-f3f7e.firebasestorage.app',
  );
}
